name: tkcms_ff_dart
description: Dart ff project
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.12.0

dependencies:
  tkcms_test:
    git:
      url: https://github.com/tekartikprj/tkcms.git
      path: packages/tkcms_test
  firebase_functions: ">=0.6.0"
  tekartik_firebase_functions_admin_sdk:
    git:
      url: https://github.com/tekartik/firebase_admin_sdk.dart
      path: firebase_functions_admin_sdk
  tekartik_firebase_functions_admin_sdk_http:
    git:
      url: https://github.com/tekartik/firebase_admin_sdk.dart
      path: firebase_functions_admin_sdk_http
  tkcms_common:
    git:
      url: https://github.com/tekartikprj/tkcms.git
      path: packages/tkcms_common
  tekartik_firebase_functions_call_http:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: functions_call_http
  tekartik_firebase_functions_call:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: functions_call
  tekartik_firebase_emulator:
    git:
      url: https://github.com/tekartik/firebase_node.dart
      path: firebase_emulator
dev_dependencies:
  lints: ">=6.1.0"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
resolution: workspace
