name: tkcms_ff
description: Firebase cloud fonctions
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  tekartik_firebase_functions_node:
    git:
      url: https://github.com/tekartik/firebase_node.dart
      path: functions_node
      ref: dart3a
    version: '>=0.4.2'
  tekartik_firebase_firestore_node:
    git:
      url: https://github.com/tekartik/firebase_node.dart
      path: firestore_node
      ref: dart3a
    version: '>=0.8.1'
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_http
    version: '>=0.1.0'
  cv:
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart3a
    version: '>=0.8.0'
  tekartik_http_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      path: http_node
      ref: dart3a
  path:
  http:
  tkcms_common:
    git:
      url: https://github.com/tekartikprj/tkcms.git
      ref: dart3a
      path: packages/tkcms_common
dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.21.0'
  tekartik_app_node_build_menu:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      ref: dart3a
      path: app_build_menu
    version: '>=0.3.0'
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart3a
    version: '>=0.1.0'

  # needed node dependencies
  build_web_compilers:
  build_runner:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a
  dev_build: '>=0.16.5-4'

dependency_overrides:
  tkcms_common:
    path: ../tkcms_common
