name: tkcms_common
description: A starting point for Dart libraries or applications.
version: 0.1.0
publish_to: none

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  path:
  http:
  tekartik_app_cv_firestore:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_cv_firestore
    version: '>=0.10.3'
  tekartik_firebase_functions:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
      ref: dart3a
    version: '>=0.2.1'
  tekartik_firebase_functions_http:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions_http
      ref: dart3a
    version: '>=0.2.1'
  tekartik_firebase_rest:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_rest
      ref: dart3a
    version: '>=0.6.2'
  tekartik_firebase_firestore_rest:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_rest
      ref: dart3a
    version: '>=0.8.0'
  tekartik_firebase_storage_rest:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage_rest
      ref: dart3a
    version: '>=0.8.0'
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart3a
    version: '>=0.9.3'
  tekartik_firebase_storage:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage
      ref: dart3a
    version: '>=0.8.0'
  tekartik_firebase_storage_fs:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage_fs
      ref: dart3a
    version: '>=0.4.0'
  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart3a
    version: '>=0.8.0'
  tekartik_firebase_auth_local:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth_local
      ref: dart3a
    version: '>=0.3.8'
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
      ref: dart3a
    version: '>=0.8.0'
  tekartik_app_crypto:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_crypto
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_http
    version: '>=0.1.0'
dev_dependencies:
  lints: '>=2.1.0'
  test: '>=1.24.0'
